In [13]:
from numpy import *
a = array([(1,2,3),(4,5,6)])
print(a)
print()
print(a.ravel())
# ravel() fun is used to  change 2D dimension into 1D array.

[[1 2 3]
 [4 5 6]]

[1 2 3 4 5 6]


In [12]:
from numpy import *
a = array([(1,2,3),(4,5,6)])
b = array([(1,2,3),(4,5,6)])
print(a)
print()
print(hstack((a,b)))
# hstack() used for horizontal(row) stacking.
# it takes array name as arguments.
print()
print(vstack((a,b)))
# hstack() used for vertical(column) stacking.
# it takes array name as arguments.


[[1 2 3]
 [4 5 6]]

[[1 2 3 1 2 3]
 [4 5 6 4 5 6]]

[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]


In [11]:
from numpy import *
a = array([(1,2,3),(4,5,5)])
print(a)
print()

# print()
print(a.sum(axis=0))
print()
print(a.sum(axis=1))

[[1 2 3]
 [4 5 5]]

[5 7 8]

[ 6 14]


In [10]:
print("hello",end = " ")
print("World!")


hello World!


In [9]:
from numpy import *
arr1 = zeros(5)
arr2 = ones(5)
arr3 = arange(1,10,2)
arr4 = linspace(1,3,10)
print(arr1)
print(arr2)
print(arr3)
print(arr4)

[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]
[1 3 5 7 9]
[1.         1.22222222 1.44444444 1.66666667 1.88888889 2.11111111
 2.33333333 2.55555556 2.77777778 3.        ]


In [8]:
from numpy import *
arr1 = array([
    [1,2,3],
    [4,5,6],
    [7,8,9],
    [10,11,12]
])
print(arr1)
# convert an array in 3D array
arr2= arr1.reshape(2,2,3)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [7]:
# coverting a 1D array into 2D array.
from numpy import *
arr1 = array([1,2,3,4])
arr2 = arr1.reshape(2,2)
# reshape() fun is used to change 1D array into 2D or 3D array. 
# It takes no. of rows and columns as an argument.
print(arr2)

[[1 2]
 [3 4]]


In [6]:
from numpy import *
arr1 = array([
                [1,2,3],
                [4,5,6],
                [7,8,9]
])
             
print(arr1)
print(arr1[2,2])
print("After converting 3D array into 1D array.")
arr2 = arr1.flatten()
# flatten() fun is used to change the dimension of the array.
print(arr2)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
9
After converting 3D array into 1D array.
[1 2 3 4 5 6 7 8 9]


In [5]:
# making 2D array
from numpy import *
# arr1= array([{1,2},{3,4}])
arr2= array([[1,2],[3,4]])
# print(arr1)
print(arr2)
# print(arr1.ndim)
print("the dimension of arr2 is:",arr2.ndim)
print("the no of rows and columns is:",arr2.shape)
print("the total no of elements is:",arr2.size)


[[1 2]
 [3 4]]
the dimension of arr2 is: 2
the no of rows and columns is: (2, 2)
the total no of elements is: 4


In [4]:
import numpy as np
arr1 = np.array([1,2,3,4,5])
print(arr1)
# arr2= np.array([5])
arr2 = arr1;
print(arr2);
print(type(arr2))
print(arr2.dtype)
print(concatenate([arr1,arr2]))

[1 2 3 4 5]
[1 2 3 4 5]
<class 'numpy.ndarray'>
int32
[1 2 3 4 5 1 2 3 4 5]


In [3]:
from numpy import *
arr1 = array([1,2,3,4,5])
print(arr1)
print(log(arr1))
print(sqrt(arr1))
# print()
print(sum(arr1))
print(max(arr1))
print(min(arr1))
arr2= array([0,30,45,90])
print(sin(arr2))

[1 2 3 4 5]
[0.         0.69314718 1.09861229 1.38629436 1.60943791]
[1.         1.41421356 1.73205081 2.         2.23606798]
15
5
1
[ 0.         -0.98803162  0.85090352  0.89399666]


In [2]:
print("hello")

hello


In [1]:
print(4+4)

8
