In [1]:
#import essential libraties
import numpy as np
import pandas as pd 

In [2]:
dataset = pd.read_csv('taxi.csv')
dataset.shape
# shape apki file ka size btata hai 

(27, 5)

In [3]:
dataset.head()
# head starting 5 line print krta hai 

Priceperweek  Population  Monthlyincome  Averageparkingpermonth  \
0            15     1800000           5800                      50   
1            15     1790000           6200                      50   
2            15     1780000           6400                      60   
3            25     1778000           6500                      60   
4            25     1750000           6550                      60   

   Numberofweeklyriders  
0                192000  
1                190400  
2                191200  
3                177600  
4                176800

In [4]:
dataset.isnull().sum()
#isnull sum kr dega colunms ke bese pr.  

Priceperweek              0
Population                0
Monthlyincome             0
Averageparkingpermonth    0
Numberofweeklyriders      0
dtype: int64

In [5]:
dataset = pd.read_csv('taxi.csv')
dataset

Priceperweek  Population  Monthlyincome  Averageparkingpermonth  \
0             15     1800000           5800                      50   
1             15     1790000           6200                      50   
2             15     1780000           6400                      60   
3             25     1778000           6500                      60   
4             25     1750000           6550                      60   
5             25     1740000           6580                      70   
6             25     1725000           8200                      75   
7             30     1725000           8600                      75   
8             30     1720000           8800                      75   
9             30     1705000           9200                      80   
10            30     1710000           9630                      80   
11            40     1700000          10570                      80   
12            40     1695000          11330                      85   
13            40     1695000          11600                     100   
14            40     1690000          11800                     105   
15            40     1630000          11830                     105   
16            65     1640000          12650                     105   
17           102     1635000          13000                     110   
18            75     1630000          13224                     125   
19            75     1620000          13766                     130   
20            75     1615000          14010                     150   
21            80     1605000          14468                     155   
22            86     1590000          15000                     165   
23            98     1595000          15200                     175   
24            87     1590000          15600                     175   
25            77     1600000          16000                     190   
26            63     1610000          16200                     200   

    Numberofweeklyriders  
0                 192000  
1                 190400  
2                 191200  
3                 177600  
4                 176800  
5                 178400  
6                 180800  
7                 175200  
8                 174400  
9                 173920  
10                172800  
11                163200  
12                161600  
13                161600  
14                160800  
15                159200  
16                148800  
17                115696  
18                147200  
19                150400  
20                152000  
21                136000  
22                126240  
23                123888  
24                126080  
25                151680  
26                152800

In [6]:
# separate dataset into dependent and independent variables
X = dataset.iloc[:,:-1].values
y = dataset.iloc[:,4].values
X
y

array([192000, 190400, 191200, 177600, 176800, 178400, 180800, 175200,
       174400, 173920, 172800, 163200, 161600, 161600, 160800, 159200,
       148800, 115696, 147200, 150400, 152000, 136000, 126240, 123888,
       126080, 151680, 152800], dtype=int64)

In [7]:
# split dataset into traning dataset and testing dataset
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.4,random_state=0)


In [8]:
X_train

array([[     15, 1790000,    6200,      50],
       [     30, 1710000,    9630,      80],
       [     63, 1610000,   16200,     200],
       [     77, 1600000,   16000,     190],
       [     30, 1720000,    8800,      75],
       [     25, 1725000,    8200,      75],
       [     25, 1750000,    6550,      60],
       [     75, 1630000,   13224,     125],
       [     30, 1705000,    9200,      80],
       [     30, 1725000,    8600,      75],
       [     86, 1590000,   15000,     165],
       [     25, 1778000,    6500,      60],
       [     15, 1800000,    5800,      50],
       [     80, 1605000,   14468,     155],
       [     40, 1630000,   11830,     105],
       [     40, 1695000,   11330,      85]], dtype=int64)

In [9]:
X_test

array([[     15, 1780000,    6400,      60],
       [     87, 1590000,   15600,     175],
       [     40, 1690000,   11800,     105],
       [    102, 1635000,   13000,     110],
       [     25, 1740000,    6580,      70],
       [     40, 1700000,   10570,      80],
       [     98, 1595000,   15200,     175],
       [     40, 1695000,   11600,     100],
       [     75, 1620000,   13766,     130],
       [     75, 1615000,   14010,     150],
       [     65, 1640000,   12650,     105]], dtype=int64)

In [10]:
y_train

array([190400, 172800, 152800, 151680, 174400, 180800, 176800, 147200,
       173920, 175200, 126240, 177600, 192000, 136000, 159200, 161600],
      dtype=int64)

In [11]:
y_test

array([191200, 126080, 160800, 115696, 178400, 163200, 123888, 161600,
       150400, 152000, 148800], dtype=int64)

In [17]:
from sklearn.linear_model import LinearRegression
reg = LinearRegression()
reg.fit(X_train,y_train) 

LinearRegression()

In [19]:
#pickling me ham binary format me conversion kr save kr dete hai 
import pickle 

In [20]:
pickle.dump(reg,open('taxi.pkl','wb'))


In [21]:
#Test the Model 
model = pickle.load(open('taxi.pkl','rb'))